-- facilities テーブルの id カラムを GENERATED BY DEFAULT に変更
-- これにより、seedデータで明示的にIDを指定できるようになる

ALTER TABLE public.facilities
ALTER COLUMN id DROP IDENTITY IF EXISTS;

ALTER TABLE public.facilities
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
