-- =============================================================================
-- 006: 施設画像テーブルとStorage設定
-- =============================================================================
-- - facility_images: 施設画像のURL情報を格納
-- - facility-images バケット: Supabase Storage設定
-- - manage_facility_images: 画像一括更新用RPC関数
-- =============================================================================

-- -----------------------------------------------------------------------------
-- facility_images テーブル
-- 施設画像のURL情報を格納
-- -----------------------------------------------------------------------------
CREATE TABLE public.facility_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id BIGINT NOT NULL REFERENCES public.facilities(id) ON DELETE CASCADE,
    image_type TEXT NOT NULL CHECK (image_type IN ('thumbnail', 'gallery')),
    image_url TEXT NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.facility_images ENABLE ROW LEVEL SECURITY;

CREATE POLICY "select_public"
    ON public.facility_images
    FOR SELECT
    USING (true);

CREATE POLICY "insert_facility_staff_or_admin"
    ON public.facility_images
    FOR INSERT
    TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.facility_profiles fp
            WHERE fp.facility_id = facility_images.facility_id
            AND fp.user_id = auth.uid()
        )
        OR EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id = auth.uid() AND p.role = 'admin'
        )
    );

CREATE POLICY "update_facility_staff_or_admin"
    ON public.facility_images
    FOR UPDATE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.facility_profiles fp
            WHERE fp.facility_id = facility_images.facility_id
            AND fp.user_id = auth.uid()
        )
        OR EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id = auth.uid() AND p.role = 'admin'
        )
    );

CREATE POLICY "delete_facility_staff_or_admin"
    ON public.facility_images
    FOR DELETE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.facility_profiles fp
            WHERE fp.facility_id = facility_images.facility_id
            AND fp.user_id = auth.uid()
        )
        OR EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id = auth.uid() AND p.role = 'admin'
        )
    );

CREATE INDEX idx_facility_images_facility_id ON public.facility_images (facility_id);
CREATE INDEX idx_facility_images_type_order ON public.facility_images (facility_id, image_type, display_order);

-- サムネイル画像は施設ごとに1枚のみ
CREATE UNIQUE INDEX idx_unique_thumbnail
    ON public.facility_images (facility_id)
    WHERE image_type = 'thumbnail';

-- ギャラリー画像の順序は施設ごとにユニーク
CREATE UNIQUE INDEX idx_unique_gallery_order
    ON public.facility_images (facility_id, display_order)
    WHERE image_type = 'gallery';

CREATE TRIGGER update_facility_images_updated_at
    BEFORE UPDATE ON public.facility_images
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

COMMENT ON TABLE public.facility_images IS '施設画像のURLとメタデータを格納するテーブル';
COMMENT ON COLUMN public.facility_images.image_type IS '画像タイプ: thumbnail(一覧用サムネイル) または gallery(詳細画面用ギャラリー)';
COMMENT ON COLUMN public.facility_images.display_order IS 'ギャラリー画像の表示順序（0-2）。サムネイルは常に0';

-- -----------------------------------------------------------------------------
-- Supabase Storage バケットの作成
-- facility-images: 施設画像を格納するパブリックバケット
-- -----------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'facility-images',
    'facility-images',
    true,
    5242880, -- 5MB
    ARRAY['image/webp']
)
ON CONFLICT (id) DO NOTHING;

-- バケットのRLSポリシー

-- 全員が閲覧可能
CREATE POLICY "Public read access"
    ON storage.objects
    FOR SELECT
    USING (bucket_id = 'facility-images');

-- 認証済みユーザーがアップロード可能（施設担当者または管理者）
CREATE POLICY "Authenticated users can upload"
    ON storage.objects
    FOR INSERT
    TO authenticated
    WITH CHECK (
        bucket_id = 'facility-images'
        AND (
            -- パスから facility_id を抽出して権限チェック
            -- パスフォーマット: {facility_id}/{image_type}/{filename}
            EXISTS (
                SELECT 1 FROM public.facility_profiles fp
                WHERE fp.facility_id = split_part(name, '/', 1)::bigint
                AND fp.user_id = auth.uid()
            )
            OR EXISTS (
                SELECT 1 FROM public.profiles p
                WHERE p.id = auth.uid() AND p.role = 'admin'
            )
        )
    );

-- 認証済みユーザーが削除可能（施設担当者または管理者）
CREATE POLICY "Authenticated users can delete"
    ON storage.objects
    FOR DELETE
    TO authenticated
    USING (
        bucket_id = 'facility-images'
        AND (
            EXISTS (
                SELECT 1 FROM public.facility_profiles fp
                WHERE fp.facility_id = split_part(name, '/', 1)::bigint
                AND fp.user_id = auth.uid()
            )
            OR EXISTS (
                SELECT 1 FROM public.profiles p
                WHERE p.id = auth.uid() AND p.role = 'admin'
            )
        )
    );

-- -----------------------------------------------------------------------------
-- manage_facility_images: 施設画像の一括更新（削除・追加）をトランザクション内で実行
-- ユニーク制約 (facility_id, display_order) 違反を防ぐため、削除を先に行う
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.manage_facility_images(
    p_facility_id BIGINT,
    p_delete_ids BIGINT[] DEFAULT '{}',
    p_new_images JSONB DEFAULT '[]'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_deleted_urls TEXT[] := '{}';
    v_inserted_ids BIGINT[] := '{}';
    v_image JSONB;
    v_new_id BIGINT;
    v_deleted_url TEXT;
BEGIN
    -- 1. 削除対象の画像URLを取得（Storage削除用に返却）
    SELECT array_agg(image_url)
    INTO v_deleted_urls
    FROM facility_images
    WHERE id = ANY(p_delete_ids)
      AND facility_id = p_facility_id;

    -- 2. 画像を削除
    DELETE FROM facility_images
    WHERE id = ANY(p_delete_ids)
      AND facility_id = p_facility_id;

    -- 3. 新しい画像を挿入
    FOR v_image IN SELECT * FROM jsonb_array_elements(p_new_images)
    LOOP
        INSERT INTO facility_images (facility_id, image_type, image_url, display_order)
        VALUES (
            p_facility_id,
            v_image->>'image_type',
            v_image->>'image_url',
            (v_image->>'display_order')::INTEGER
        )
        RETURNING id INTO v_new_id;

        v_inserted_ids := array_append(v_inserted_ids, v_new_id);
    END LOOP;

    -- 4. 結果を返却
    RETURN jsonb_build_object(
        'deleted_urls', to_jsonb(COALESCE(v_deleted_urls, '{}')),
        'inserted_ids', to_jsonb(v_inserted_ids)
    );
END;
$$;

-- RLSバイパスのため SECURITY DEFINER を使用
-- 呼び出し元でのアクセス制御は別途行う

COMMENT ON FUNCTION public.manage_facility_images IS '施設画像の一括更新（削除・追加）をアトミックに実行するRPC関数';
