-- facilities テーブル
-- 施設の基本情報を格納
CREATE TABLE public.facilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    corporation TEXT NOT NULL,
    postal_code TEXT NOT NULL,
    phone TEXT NOT NULL,
    prefecture TEXT NOT NULL,
    city TEXT NOT NULL,
    address_detail TEXT NOT NULL,
    established_year INTEGER NOT NULL CHECK (established_year BETWEEN 1800 AND date_part('year', now())),
    annex_facilities JSONB DEFAULT '[]'::jsonb NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- 併設施設の妥当性チェック（配列型であることを確認）
    CONSTRAINT chk_annex_facilities_is_array CHECK (jsonb_typeof(annex_facilities) = 'array')
);

-- RLSを有効化
ALTER TABLE public.facilities ENABLE ROW LEVEL SECURITY;

-- すべてのユーザーが閲覧可能
CREATE POLICY "select_public"
    ON public.facilities
    FOR SELECT
    USING (true);

-- 管理者のみ挿入可能（新規施設は担当者紐付け前のため）
CREATE POLICY "insert_admin_only"
    ON public.facilities
    FOR INSERT
    TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id = auth.uid() AND p.role = 'admin'
        )
    );

-- インデックスを作成
CREATE INDEX IF NOT EXISTS idx_facilities_name ON public.facilities (name);
CREATE INDEX idx_facilities_annex_facilities_gin ON public.facilities USING gin(annex_facilities);

-- updated_at 自動更新（汎用関数を使用）
CREATE TRIGGER update_facilities_updated_at
    BEFORE UPDATE ON public.facilities
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- カラムコメント
COMMENT ON COLUMN public.facilities.annex_facilities IS '併設施設情報を格納する JSONB 配列。各要素は {name: string, type: string} の形式';
