-- facility_images テーブル
-- 施設画像のURL情報を格納
CREATE TABLE public.facility_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id BIGINT NOT NULL REFERENCES public.facilities(id) ON DELETE CASCADE,
    image_type TEXT NOT NULL CHECK (image_type IN ('thumbnail', 'gallery')),
    image_url TEXT NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- RLSを有効化
ALTER TABLE public.facility_images ENABLE ROW LEVEL SECURITY;

-- すべてのユーザーが閲覧可能
CREATE POLICY "select_public"
    ON public.facility_images
    FOR SELECT
    USING (true);

-- 施設担当者と管理者のみ挿入・更新・削除可能
CREATE POLICY "insert_facility_staff_or_admin"
    ON public.facility_images
    FOR INSERT
    TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.facility_profiles fp
            WHERE fp.facility_id = facility_images.facility_id
            AND fp.user_id = auth.uid()
        )
        OR EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id = auth.uid() AND p.role = 'admin'
        )
    );

CREATE POLICY "update_facility_staff_or_admin"
    ON public.facility_images
    FOR UPDATE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.facility_profiles fp
            WHERE fp.facility_id = facility_images.facility_id
            AND fp.user_id = auth.uid()
        )
        OR EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id = auth.uid() AND p.role = 'admin'
        )
    );

CREATE POLICY "delete_facility_staff_or_admin"
    ON public.facility_images
    FOR DELETE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.facility_profiles fp
            WHERE fp.facility_id = facility_images.facility_id
            AND fp.user_id = auth.uid()
        )
        OR EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id = auth.uid() AND p.role = 'admin'
        )
    );

-- インデックスを作成
CREATE INDEX idx_facility_images_facility_id ON public.facility_images (facility_id);
CREATE INDEX idx_facility_images_type_order ON public.facility_images (facility_id, image_type, display_order);

-- サムネイル画像は施設ごとに1枚のみ
CREATE UNIQUE INDEX idx_unique_thumbnail 
    ON public.facility_images (facility_id) 
    WHERE image_type = 'thumbnail';

-- ギャラリー画像の順序は施設ごとにユニーク
CREATE UNIQUE INDEX idx_unique_gallery_order 
    ON public.facility_images (facility_id, display_order) 
    WHERE image_type = 'gallery';

-- updated_at 自動更新
CREATE TRIGGER update_facility_images_updated_at
    BEFORE UPDATE ON public.facility_images
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- カラムコメント
COMMENT ON TABLE public.facility_images IS '施設画像のURLとメタデータを格納するテーブル';
COMMENT ON COLUMN public.facility_images.image_type IS '画像タイプ: thumbnail(一覧用サムネイル) または gallery(詳細画面用ギャラリー)';
COMMENT ON COLUMN public.facility_images.display_order IS 'ギャラリー画像の表示順序（0-2）。サムネイルは常に0';
